name: search-rubygems

on:
  schedule:
    - cron: "0 14 * * *"
  push:
  workflow_dispatch:

jobs:
  search-rubygems:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: actions/search_rubygems/Gemfile
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1 # https://github.com/ruby/setup-ruby
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - name: bundle install
      run: |
        bundle install
    - name: run search-rubygems
      run: |
        bundle exec ruby actions/search_rubygems/execute.rb
      env: 
        LINE_CHANNEL_SECRET: ${{ env.LINE_CHANNEL_SECRET }}
        LINE_CHANNEL_TOKEN: ${{ env.LINE_CHANNEL_TOKEN }}
        LINE_USER_ID: ${{ env.LINE_USER_ID }}
