name: search_rubygems

on:
  schedule:
    - cron: "0 14 * * *"
  push:
  workflow_dispatch:

jobs:
  ruboty-sonar:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: actions/search_rubygems/Gemfile
    steps:
    - uses: actions/checkout@v3
    # https://github.com/ruby/setup-ruby
    - uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - name: bundle install
      run: |
        bundle install
    - name: run ruboty-sonar
      run: |
        bundle exec ruby actions/search_rubygems/execute.rb
